import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const styles = {
  body: {
    margin: 0,
    padding: 0,
    minHeight: '100vh',
  },
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body style={styles.body}>{children}</body>
    </html>
  );
}
