import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { loadProducts } from '../../lib/products';
import './globals.css';
import type { InferGetStaticPropsType, GetStaticProps } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// export async function GetStaticProps() {
//   const response = await loadPosts(
//     `${process.env.NEXT_PUBLIC_STRAPI_API_URL}/blog-posts`
//   );
//   console.log(response);
//   return { props: { response } };
// }
